version: '2'

services:
  weacast:
    build: .
    container_name: weacast
    image: weacast/weacast
    links:
      - mongodb-weacast:mongodb
    ports:
      - 8081:8081
    networks:
      - weacast
    environment:
      - DB_URL=mongodb://mongodb:27017/weacast
  mongodb-weacast:
    container_name: mongodb-weacast
    image: mongo
    volumes:
      - mongodb_weacast:/data/db
    networks:
      - weacast

volumes:
  mongodb_weacast:

networks:
  weacast:
